
modLoader="javafml"
loaderVersion="[35,)"
license="GNU GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues"
logoFile="antiqueatlas_icon.png"
[[mods]]
modId="antiqueatlas"
version="${version}"
displayName="Antique Atlas"
displayURL="https://www.curseforge.com/minecraft/mc-mods/antique-atlas"
credits="Hunternif, Kenkron, tyra314, , osipxd, thecodewarrior, TehNut, crafteverywhere, coolAlias, Ruukas97, Mazdallier, chesterccj305, asiekierka, sam-kirby, esotericist, dadodollabela, Yulife, Waterrail, The-Fireplace, TBM13, Rikshy, GirafiStudios, DrCopernicus, DBotThePony, AugiteSoul, Stereowalker"
authors="Hunternif"
description='''
Antique Atlas is a book that acts like a map featuring infinite scrolling, zoom and custom labeled markers. The map is generated around the player by calculating the average biome in each 16x16 chunk.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.antiqueatlas]]
    # the modid of the dependency
    modId="forge"
    mandatory=true
    versionRange="[35.1.28,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.antiqueatlas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.antiqueatlas]]
    modId="cloth-config"
    mandatory=true
    versionRange="[4.11.15,)"
    ordering="NONE"
    side="BOTH"