package hunternif.mc.atlas.client;

import hunternif.mc.atlas.AntiqueAtlasMod;
import net.minecraft.util.ResourceLocation;

public class Textures {
	public static final String MOD_PREFIX = AntiqueAtlasMod.ID + ":";
	public static final String GUI = MOD_PREFIX + "textures/gui/";
	public static final String GUI_TILES = GUI + "tiles/";
	public static final String GUI_MARKERS = GUI + "markers/";
	public static final String GUI_SCALEBAR = GUI + "scalebar/";
	
	public static final ResourceLocation BOOK = new ResourceLocation(GUI + "book.png");
	public static final ResourceLocation EXPORTED_BG = new ResourceLocation(GUI + "exportedBG.png");
	public static final ResourceLocation BOOK_FRAME = new ResourceLocation(GUI + "bookFrame.png");
	public static final ResourceLocation BTN_ARROWS = new ResourceLocation(GUI + "navigateArrows.png");
	public static final ResourceLocation BTN_POSITION = new ResourceLocation(GUI + "position.png");
	public static final ResourceLocation BOOKMARKS = new ResourceLocation(GUI + "bookmarks.png");
	public static final ResourceLocation PLAYER = new ResourceLocation(GUI + "player.png");
	public static final ResourceLocation SCROLLBAR_HOR = new ResourceLocation(GUI + "scrollbar_hor.png");
	public static final ResourceLocation SCROLLBAR_VER = new ResourceLocation(GUI + "scrollbar_ver.png");
	public static final ResourceLocation MARKER_FRAME_ON = new ResourceLocation(GUI + "marker_frame_on.png");
	public static final ResourceLocation MARKER_FRAME_OFF = new ResourceLocation(GUI + "marker_frame_off.png");
	public static final ResourceLocation ERASER = new ResourceLocation(GUI + "eraser.png");
	
	public static final ResourceLocation SCALEBAR_4 = new ResourceLocation(GUI_SCALEBAR + "scalebar_4.png");
	public static final ResourceLocation SCALEBAR_8 = new ResourceLocation(GUI_SCALEBAR + "scalebar_8.png");
	public static final ResourceLocation SCALEBAR_16 = new ResourceLocation(GUI_SCALEBAR + "scalebar_16.png");
	public static final ResourceLocation SCALEBAR_32 = new ResourceLocation(GUI_SCALEBAR + "scalebar_32.png");
	public static final ResourceLocation SCALEBAR_64 = new ResourceLocation(GUI_SCALEBAR + "scalebar_64.png");
	public static final ResourceLocation SCALEBAR_128 = new ResourceLocation(GUI_SCALEBAR + "scalebar_128.png");
	public static final ResourceLocation SCALEBAR_256 = new ResourceLocation(GUI_SCALEBAR + "scalebar_256.png");
	public static final ResourceLocation SCALEBAR_512 = new ResourceLocation(GUI_SCALEBAR + "scalebar_512.png");
	
	public static final ResourceLocation ICON_EXPORT = new ResourceLocation(GUI + "icon_export.png");
	public static final ResourceLocation ICON_MARKER = new ResourceLocation(GUI + "icon_marker.png");
	public static final ResourceLocation ICON_DELETE_MARKER = new ResourceLocation(GUI + "icon_del_marker.png");
	
	public static final ResourceLocation MARKER_GOOGLE_MARKER = new ResourceLocation(GUI_MARKERS + "google_marker.png");
	public static final ResourceLocation MARKER_RED_X_LARGE = new ResourceLocation(GUI_MARKERS + "red_x_large.png");
	public static final ResourceLocation MARKER_RED_X_SMALL = new ResourceLocation(GUI_MARKERS + "red_x_small.png");
	public static final ResourceLocation MARKER_VILLAGE = new ResourceLocation(GUI_MARKERS + "village.png");
	
	public static final ResourceLocation TILE_TEST = new ResourceLocation(GUI_TILES + "test.png");
	public static final ResourceLocation TILE_MOUNTAINS = new ResourceLocation(GUI_TILES + "mountains.png");
	public static final ResourceLocation TILE_MOUNTAINS2 = new ResourceLocation(GUI_TILES + "mountains2.png");
	public static final ResourceLocation TILE_MOUNTAINS3 = new ResourceLocation(GUI_TILES + "mountains3.png");
	public static final ResourceLocation TILE_MOUNTAINS4 = new ResourceLocation(GUI_TILES + "mountains4.png");
	public static final ResourceLocation TILE_SNOW_CAPS = new ResourceLocation(GUI_TILES + "snow_caps.png");
	public static final ResourceLocation TILE_SNOW_HILLS = new ResourceLocation(GUI_TILES + "snow_hills.png");
	public static final ResourceLocation TILE_SNOW_HILLS2 = new ResourceLocation(GUI_TILES + "snow_hills2.png");
	public static final ResourceLocation TILE_WATER = new ResourceLocation(GUI_TILES + "water.png");
	public static final ResourceLocation TILE_WATER2 = new ResourceLocation(GUI_TILES + "water2.png");
	public static final ResourceLocation TILE_ICE_BORDER = new ResourceLocation(GUI_TILES + "ice_border.png");
	public static final ResourceLocation TILE_ICE_NOBORDER = new ResourceLocation(GUI_TILES + "ice_noborder.png");
	public static final ResourceLocation TILE_FOREST = new ResourceLocation(GUI_TILES + "forest.png");
	public static final ResourceLocation TILE_FOREST2 = new ResourceLocation(GUI_TILES + "forest2.png");
	public static final ResourceLocation TILE_FOREST_HILLS = new ResourceLocation(GUI_TILES + "forest_hills.png");
	public static final ResourceLocation TILE_FOREST_HILLS2 = new ResourceLocation(GUI_TILES + "forest_hills2.png");
	public static final ResourceLocation TILE_HILLS = new ResourceLocation(GUI_TILES + "hills.png");
	public static final ResourceLocation TILE_PINES = new ResourceLocation(GUI_TILES + "pines.png");
	public static final ResourceLocation TILE_PINES2 = new ResourceLocation(GUI_TILES + "pines2.png");
	public static final ResourceLocation TILE_PINES3 = new ResourceLocation(GUI_TILES + "pines3.png");
	public static final ResourceLocation TILE_PINES_HILLS = new ResourceLocation(GUI_TILES + "pines_hills.png");
	public static final ResourceLocation TILE_PINES_HILLS2 = new ResourceLocation(GUI_TILES + "pines_hills2.png");
	public static final ResourceLocation TILE_PINES_HILLS3 = new ResourceLocation(GUI_TILES + "pines_hills3.png");
	public static final ResourceLocation TILE_MEGA_SPRUCE = new ResourceLocation(GUI_TILES + "mega_spruce.png");
	public static final ResourceLocation TILE_MEGA_SPRUCE2 = new ResourceLocation(GUI_TILES + "mega_spruce2.png");
	public static final ResourceLocation TILE_MEGA_TAIGA = new ResourceLocation(GUI_TILES + "mega_taiga.png");
	public static final ResourceLocation TILE_MEGA_TAIGA2 = new ResourceLocation(GUI_TILES + "mega_taiga2.png");
	public static final ResourceLocation TILE_MEGA_SPRUCE_HILLS = new ResourceLocation(GUI_TILES + "mega_spruce_hills.png");
	public static final ResourceLocation TILE_MEGA_SPRUCE_HILLS2 = new ResourceLocation(GUI_TILES + "mega_spruce_hills2.png");
	public static final ResourceLocation TILE_MEGA_TAIGA_HILLS = new ResourceLocation(GUI_TILES + "mega_taiga_hills.png");
	public static final ResourceLocation TILE_MEGA_TAIGA_HILLS2 = new ResourceLocation(GUI_TILES + "mega_taiga_hills2.png");
	public static final ResourceLocation TILE_SAND = new ResourceLocation(GUI_TILES + "sand.png");
	public static final ResourceLocation TILE_SAND2 = new ResourceLocation(GUI_TILES + "sand2.png");
	public static final ResourceLocation TILE_SHORE = new ResourceLocation(GUI_TILES + "shore.png");
	public static final ResourceLocation TILE_SHORE2 = new ResourceLocation(GUI_TILES + "shore2.png");
	public static final ResourceLocation TILE_ROCK_SHORE = new ResourceLocation(GUI_TILES + "rock_shore.png");
	public static final ResourceLocation TILE_SHORE3 = new ResourceLocation(GUI_TILES + "shore3.png");
	public static final ResourceLocation TILE_GRASS = new ResourceLocation(GUI_TILES + "grass.png");
	public static final ResourceLocation TILE_GRASS2 = new ResourceLocation(GUI_TILES + "grass2.png");
	public static final ResourceLocation TILE_GRASS3 = new ResourceLocation(GUI_TILES + "grass3.png");
	public static final ResourceLocation TILE_GRASS4 = new ResourceLocation(GUI_TILES + "grass4.png");
	public static final ResourceLocation TILE_SUNFLOWERS = new ResourceLocation(GUI_TILES + "sunflowers.png");
	public static final ResourceLocation TILE_SUNFLOWERS2 = new ResourceLocation(GUI_TILES + "sunflowers2.png");
	public static final ResourceLocation TILE_SNOW = new ResourceLocation(GUI_TILES + "snow.png");
	public static final ResourceLocation TILE_SNOW1 = new ResourceLocation(GUI_TILES + "snow1.png");
	public static final ResourceLocation TILE_SNOW2 = new ResourceLocation(GUI_TILES + "snow2.png");
	public static final ResourceLocation TILE_SNOW3 = new ResourceLocation(GUI_TILES + "snow3.png");
	public static final ResourceLocation TILE_SNOW4 = new ResourceLocation(GUI_TILES + "snow4.png");
	public static final ResourceLocation TILE_SNOW5 = new ResourceLocation(GUI_TILES + "snow5.png");
	public static final ResourceLocation TILE_SNOW6 = new ResourceLocation(GUI_TILES + "snow6.png");
	public static final ResourceLocation TILE_SNOW_PINES = new ResourceLocation(GUI_TILES + "snow_pines.png");
	public static final ResourceLocation TILE_SNOW_PINES2 = new ResourceLocation(GUI_TILES + "snow_pines2.png");
	public static final ResourceLocation TILE_SNOW_PINES3 = new ResourceLocation(GUI_TILES + "snow_pines3.png");
	public static final ResourceLocation TILE_SNOW_PINES_HILLS = new ResourceLocation(GUI_TILES + "snow_pines_hills.png");
	public static final ResourceLocation TILE_SNOW_PINES_HILLS2 = new ResourceLocation(GUI_TILES + "snow_pines_hills2.png");
	public static final ResourceLocation TILE_SNOW_PINES_HILLS3 = new ResourceLocation(GUI_TILES + "snow_pines_hills3.png");
	public static final ResourceLocation TILE_ICE_SPIKES = new ResourceLocation(GUI_TILES + "ice_spikes.png");
	public static final ResourceLocation TILE_ICE_SPIKES2 = new ResourceLocation(GUI_TILES + "ice_spikes2.png");
	public static final ResourceLocation TILE_SNOW_MOUNTAINS = new ResourceLocation(GUI_TILES + "snow_mountains.png");
	public static final ResourceLocation TILE_SNOW_MOUNTAINS2 = new ResourceLocation(GUI_TILES + "snow_mountains2.png");
	public static final ResourceLocation TILE_SWAMP = new ResourceLocation(GUI_TILES + "swamp.png");
	public static final ResourceLocation TILE_SWAMP2 = new ResourceLocation(GUI_TILES + "swamp2.png");
	public static final ResourceLocation TILE_SWAMP3 = new ResourceLocation(GUI_TILES + "swamp3.png");
	public static final ResourceLocation TILE_SWAMP4 = new ResourceLocation(GUI_TILES + "swamp4.png");
	public static final ResourceLocation TILE_SWAMP5 = new ResourceLocation(GUI_TILES + "swamp5.png");
	public static final ResourceLocation TILE_SWAMP6 = new ResourceLocation(GUI_TILES + "swamp6.png");
	public static final ResourceLocation TILE_MUSHROOM = new ResourceLocation(GUI_TILES + "mushroom.png");
	public static final ResourceLocation TILE_MUSHROOM2 = new ResourceLocation(GUI_TILES + "mushroom2.png");
	public static final ResourceLocation TILE_JUNGLE = new ResourceLocation(GUI_TILES + "jungle.png");
	public static final ResourceLocation TILE_JUNGLE2 = new ResourceLocation(GUI_TILES + "jungle2.png");
	public static final ResourceLocation TILE_JUNGLE_HILLS = new ResourceLocation(GUI_TILES + "jungle_hills.png");
	public static final ResourceLocation TILE_JUNGLE_HILLS2 = new ResourceLocation(GUI_TILES + "jungle_hills2.png");
	
	// Village:
	public static final ResourceLocation TILE_HOUSE = new ResourceLocation(GUI_TILES + "house.png");
	public static final ResourceLocation TILE_FENCE = new ResourceLocation(GUI_TILES + "fence.png");
}
